version: '2.1'

# Predefiend Zookeeper Image
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  # Predefiend Kafka Image
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: 'news-train:1:1'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # Predefiend Spark-Master Image
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - INIT_DAEMON_STEP=setup_spark

  # Predefiend Spark-Worker Image
  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'

  producer:
    build: ./data-ingestion-service/.
    environment:
      BROKER: kafka:9092
    command: 'python3 producer.py'
    depends_on:
      - kafka

  consumer:
    build: ./dataIngestionService/.
    environment:
      BROKER: kafka:9092
    command: 'python3 consumer.py'
    depends_on:
      - kafka
      - producer

  trainer:
    build: ./modelTrainingService/.
    command: 'python3 app.py '
    depends_on:
      - spark-master
      - kafka
      - producer
      - consumer

volumes:
  mongo-data:
    driver: local
